### PR TITLE
Getting started: SMS respond to incoming SMS

### PR DESCRIPTION
**Pull request by JPPortier**

### CODE REVIEW

**Comment by alex-sberna** [comment]
The only thing I noticed is the README. We don't include a README in the Verification getting started so maybe we don't need one here either? Otherwise we can add a README for Verification and modify this one to specify what it does.

**Comment by JPPortier** [comment]
> The only thing I noticed is the README. We don't include a README in the Verification getting started so maybe we don't need one here either? Otherwise we can add a README for Verification and modify this one to specify what it does.

If online doc is having enough information to transform the README as a "not having added value" we could remove READMEs from all getting started directories. 

Another alternative could be to have "single line README" with a link onto the README related to the template (client or server) used for the getting started creation

**Comment by alex-sberna** [comment]
> > The only thing I noticed is the README. We don't include a README in the Verification getting started so maybe we don't need one here either? Otherwise we can add a README for Verification and modify this one to specify what it does.
> 
> If online doc is having enough information to transform the README as a "not having added value" we could remove READMEs from all getting started directories.
> 
> Another alternative could be to have "single line README" with a link onto the README related to the template (client or server) used for the getting started creation

I think online documentation has enough information as to how to use the code, I think the README is mostly there if someone stumbles upon the code just in the repo. So, I think the single line README with links to the base template and to the online documentation would probably be sufficient.

**Review by alex-sberna — APPROVED** [review]
LGTM

**Pull request merged**
